#pragma once

/**
 * @file GeoRuleGenerator.h
 * @brief Phase G: GeoIP/GeoSite rule generation from text-format inputs.
 *
 * Optionally downloads GeoIP/GeoSite dat cache files, then reads text-format
 * GeoIP (CIDR) and GeoSite (domain) files, generates
 * merged bypass CIDR and DNS rule output files, and returns their paths
 * for the caller to append to the existing load lists.
 *
 * @details Designed to be called once at client startup when
 *          `geo-rules.enabled == true`.  Generated files are written to
 *          the configured output paths; parent directories are created
 *          automatically if they do not exist.
 *
 * Limitations (Phase G initial):
 *   - Binary geoip.dat/geosite.dat files can be downloaded and cached, but are
 *     not parsed into rules yet.
 *   - URL sources in geoip/geosite fields are not yet supported; only local
 *     file paths.  Use geoip-download-url/geosite-download-url for dat cache
 *     downloads.
 *   - append-bypass supports inline CIDR strings and local file paths.
 *   - append-dns-rules supports inline rule strings and local file paths
 *     (prefix with "rules://" to load from file).
 *   - Stable de-duplication is attempted via unordered_set but duplicate
 *     CIDRs in different notation forms may not be caught.
 *
 * @author  OPENPPP2 Team
 * @license GPL-3.0
 */

#include <ppp/stdafx.h>
#include <ppp/configurations/AppConfiguration.h>

namespace ppp {
    namespace app {
        namespace client {

            /**
             * @brief Result of a GeoRuleGenerator::Generate() invocation.
             */
            struct GeoRuleGenerateResult final {
                ppp::string     output_bypass_path;     ///< Absolute path of the generated bypass file, or empty on failure.
                ppp::string     output_dns_rules_path;  ///< Absolute path of the generated DNS rules file, or empty on failure.
                int             bypass_line_count = 0;   ///< Number of CIDR lines written to the bypass output.
                int             dns_rule_line_count = 0; ///< Number of DNS rule lines written to the DNS rules output.
                int             skipped_lines = 0;       ///< Total skipped/invalid lines across all inputs.
            };

            /**
             * @brief Generates bypass CIDR and DNS rule files from GeoIP/GeoSite text inputs.
             *
             * This class is stateless; all state is passed through the static
             * Generate() method.  Thread-safe if called from a single thread
             * (the expected startup path).
             */
            class GeoRuleGenerator final {
            public:
                /**
                 * @brief Runs the full geo-rules generation pipeline.
                 *
                 * @param config  Application configuration containing geo-rules settings.
                 * @return Result with output file paths and statistics.
                 *
                 * Workflow:
                  * 1. Download geoip-dat/geosite-dat cache files when download URLs are configured.
                  * 2. Resolve effective dns-provider-domestic (fallback to dns.servers.domestic, then "doh.pub").
                  * 3. Read and parse all GeoIP source files → collect CIDR lines.
                  * 4. Read and parse all GeoSite source files → generate DNS rule lines.
                  * 5. Process append-bypass entries (inline CIDR or file paths).
                  * 6. Process append-dns-rules entries (inline rules or rules:// file paths).
                  * 7. De-duplicate (stable) and write output files.
                  */
                static GeoRuleGenerateResult Generate(const ppp::configurations::AppConfiguration& config) noexcept;

            private:
                /**
                 * @brief Reads a text file and returns non-empty, non-comment lines.
                 * @param path File path (absolute or relative).
                 * @param lines Output vector of trimmed, non-empty lines.
                 * @return Number of lines read.
                 */
                static int ReadTextLines(const ppp::string& path, ppp::vector<ppp::string>& lines) noexcept;

                /**
                 * @brief Downloads a configured Geo dat URL into a local cache path.
                 * @param url HTTP/HTTPS URL to download from.
                 * @param output_path Local output path to write.
                 * @param label Human-readable label used in telemetry logs.
                 * @return True when no download is needed or the download succeeds.
                 */
                static bool DownloadDatFile(const ppp::string& url, const ppp::string& output_path, const char* label) noexcept;

                /**
                 * @brief Processes a single GeoIP source, appending valid CIDR lines.
                 * @param path Source file path.
                 * @param cidrs Output set of CIDR strings.
                 * @param skipped Output counter for skipped/invalid lines.
                 */
                static void ProcessGeoIpSource(const ppp::string& path, ppp::unordered_set<ppp::string>& cidrs, int& skipped) noexcept;

                /**
                 * @brief Processes a single GeoSite source, generating DNS rule lines.
                 * @param path Source file path.
                 * @param domestic_provider Effective domestic DNS provider name.
                 * @param dns_rules Output vector of DNS rule lines.
                 * @param skipped Output counter for skipped/invalid lines.
                 */
                static void ProcessGeoSiteSource(const ppp::string& path, const ppp::string& domestic_provider, ppp::vector<ppp::string>& dns_rules, int& skipped) noexcept;

                /**
                 * @brief Normalizes a domain input line into a DNS rule line.
                 * @param line Raw input line (e.g. "baidu.com", ".qq.com", "domain:taobao.com", "full:example.cn", "regexp:^.*\\.example\\.cn$").
                 * @param domestic_provider Domestic DNS provider name.
                 * @return Normalized DNS rule line, or empty if the line should be skipped.
                 */
                static ppp::string NormalizeDomainToDnsRule(const ppp::string& line, const ppp::string& domestic_provider) noexcept;

                /**
                 * @brief Ensures the parent directory of a file path exists.
                 * @param file_path Target file path.
                 * @return True when the directory exists or was successfully created.
                 */
                static bool EnsureParentDirectory(const ppp::string& file_path) noexcept;
            };

        } // namespace client
    } // namespace app
} // namespace ppp
